# Generated by Django 6.0.5 on 2026-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0003_alter_incidence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='incidence',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
