# Generated by Django 6.0.5 on 2026-05-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0004_remove_provider_api_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incidence',
        ),
    ]
