# Generated by Django 6.0.5 on 2026-05-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0005_delete_incidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Sin descripcion', max_length=500)),
                ('type', models.CharField(choices=[('nonpayment', 'Impago'), ('connection_error', 'Error de conexion'), ('devolution', 'Devolucion'), ('timeout', 'Timeout'), ('authentication_error', 'Error de autenticacion')])),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarela.transaction')),
            ],
        ),
    ]
