# Generated by Django 6.0.5 on 2026-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0007_transaction_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_state',
            field=models.CharField(choices=[('pending', 'Pago pendiente'), ('completed', 'Pago completado'), ('failed', 'Pago fallido')], default='pending'),
        ),
    ]
