# Generated by Django 6.0.5 on 2026-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0008_transaction_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_state',
            field=models.CharField(choices=[('pending', 'Pago pendiente'), ('completed', 'Pago completado'), ('failed', 'Pago fallido'), ('refunded', 'Pago devuelto')], default='pending'),
        ),
    ]
