# Generated by Django 6.0.5 on 2026-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0009_alter_transaction_payment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='environment',
            field=models.CharField(choices=[('test', 'Testing'), ('prod', 'Producción')], default='test'),
        ),
    ]
